;;; -*- Mode: lisp -*-
;;;
;;; This file has been automatically generated by cffi/c2ffi. Editing it by hand is not wise.
;;;

(UIOP/PACKAGE:DEFINE-PACKAGE #:HU.DWIM.ZLIB.FFI (:USE))

(COMMON-LISP:IN-PACKAGE #:HU.DWIM.ZLIB.FFI)

(CFFI:DEFCTYPE FUNCTION-POINTER :POINTER)

(CFFI:DEFINE-FOREIGN-LIBRARY ZLIB
  (COMMON-LISP:T (:DEFAULT "libz")))

(CFFI:USE-FOREIGN-LIBRARY ZLIB)

;; Skipped "__u_char" due to filters
;; Skipped "__u_short" due to filters
;; Skipped "__u_int" due to filters
;; Skipped "__u_long" due to filters
;; Skipped "__int8_t" due to filters
;; Skipped "__uint8_t" due to filters
;; Skipped "__int16_t" due to filters
;; Skipped "__uint16_t" due to filters
;; Skipped "__int32_t" due to filters
;; Skipped "__uint32_t" due to filters
;; Skipped "__int64_t" due to filters
;; Skipped "__uint64_t" due to filters
;; Skipped "__quad_t" due to filters
;; Skipped "__u_quad_t" due to filters
;; Skipped "__dev_t" due to filters
;; Skipped "__uid_t" due to filters
;; Skipped "__gid_t" due to filters
;; Skipped "__ino_t" due to filters
;; Skipped "__ino64_t" due to filters
;; Skipped "__mode_t" due to filters
;; Skipped "__nlink_t" due to filters
;; Skipped "__off_t" due to filters
;; Skipped "__off64_t" due to filters
;; Skipped "__pid_t" due to filters
;; Skipped "__fsid_t" due to filters
;; Skipped "__clock_t" due to filters
;; Skipped "__rlim_t" due to filters
;; Skipped "__rlim64_t" due to filters
;; Skipped "__id_t" due to filters
;; Skipped "__time_t" due to filters
;; Skipped "__useconds_t" due to filters
;; Skipped "__suseconds_t" due to filters
;; Skipped "__daddr_t" due to filters
;; Skipped "__key_t" due to filters
;; Skipped "__clockid_t" due to filters
;; Skipped "__timer_t" due to filters
;; Skipped "__blksize_t" due to filters
;; Skipped "__blkcnt_t" due to filters
;; Skipped "__blkcnt64_t" due to filters
;; Skipped "__fsblkcnt_t" due to filters
;; Skipped "__fsblkcnt64_t" due to filters
;; Skipped "__fsfilcnt_t" due to filters
;; Skipped "__fsfilcnt64_t" due to filters
;; Skipped "__fsword_t" due to filters
;; Skipped "__ssize_t" due to filters
;; Skipped "__syscall_slong_t" due to filters
;; Skipped "__syscall_ulong_t" due to filters
;; Skipped "__loff_t" due to filters
;; Skipped "__qaddr_t" due to filters
;; Skipped "__caddr_t" due to filters
;; Skipped "__intptr_t" due to filters
;; Skipped "__socklen_t" due to filters
;; Skipped "ssize_t" due to filters
;; Skipped "size_t" due to filters
;; Skipped "gid_t" due to filters
;; Skipped "uid_t" due to filters
;; Skipped "off_t" due to filters
;; Skipped "useconds_t" due to filters
;; Skipped "pid_t" due to filters
;; Skipped "intptr_t" due to filters
;; Skipped "socklen_t" due to filters
;; Skipped "access" due to filters
;; Skipped "faccessat" due to filters
;; Skipped "lseek" due to filters
;; Skipped "close" due to filters
;; Skipped "read" due to filters
;; Skipped "write" due to filters
;; Skipped "pread" due to filters
;; Skipped "pwrite" due to filters
;; Skipped "pipe" due to filters
;; Skipped "alarm" due to filters
;; Skipped "sleep" due to filters
;; Skipped "ualarm" due to filters
;; Skipped "usleep" due to filters
;; Skipped "pause" due to filters
;; Skipped "chown" due to filters
;; Skipped "fchown" due to filters
;; Skipped "lchown" due to filters
;; Skipped "fchownat" due to filters
;; Skipped "chdir" due to filters
;; Skipped "fchdir" due to filters
;; Skipped "getcwd" due to filters
;; Skipped "getwd" due to filters
;; Skipped "dup" due to filters
;; Skipped "dup2" due to filters
;; Skipped "__environ" due to filters
;; Skipped "execve" due to filters
;; Skipped "fexecve" due to filters
;; Skipped "execv" due to filters
;; Skipped "execle" due to filters
;; Skipped "execl" due to filters
;; Skipped "execvp" due to filters
;; Skipped "execlp" due to filters
;; Skipped "nice" due to filters
;; Skipped "_exit" due to filters
;; Skipped COMMON-LISP:NIL due to filters
;; Skipped COMMON-LISP:NIL due to filters
;; Skipped COMMON-LISP:NIL due to filters
;; Skipped "pathconf" due to filters
;; Skipped "fpathconf" due to filters
;; Skipped "sysconf" due to filters
;; Skipped "confstr" due to filters
;; Skipped "getpid" due to filters
;; Skipped "getppid" due to filters
;; Skipped "getpgrp" due to filters
;; Skipped "__getpgid" due to filters
;; Skipped "getpgid" due to filters
;; Skipped "setpgid" due to filters
;; Skipped "setpgrp" due to filters
;; Skipped "setsid" due to filters
;; Skipped "getsid" due to filters
;; Skipped "getuid" due to filters
;; Skipped "geteuid" due to filters
;; Skipped "getgid" due to filters
;; Skipped "getegid" due to filters
;; Skipped "getgroups" due to filters
;; Skipped "setuid" due to filters
;; Skipped "setreuid" due to filters
;; Skipped "seteuid" due to filters
;; Skipped "setgid" due to filters
;; Skipped "setregid" due to filters
;; Skipped "setegid" due to filters
;; Skipped "fork" due to filters
;; Skipped "vfork" due to filters
;; Skipped "ttyname" due to filters
;; Skipped "ttyname_r" due to filters
;; Skipped "isatty" due to filters
;; Skipped "ttyslot" due to filters
;; Skipped "link" due to filters
;; Skipped "linkat" due to filters
;; Skipped "symlink" due to filters
;; Skipped "readlink" due to filters
;; Skipped "symlinkat" due to filters
;; Skipped "readlinkat" due to filters
;; Skipped "unlink" due to filters
;; Skipped "unlinkat" due to filters
;; Skipped "rmdir" due to filters
;; Skipped "tcgetpgrp" due to filters
;; Skipped "tcsetpgrp" due to filters
;; Skipped "getlogin" due to filters
;; Skipped "getlogin_r" due to filters
;; Skipped "setlogin" due to filters
;; Skipped "optarg" due to filters
;; Skipped "optind" due to filters
;; Skipped "opterr" due to filters
;; Skipped "optopt" due to filters
;; Skipped "getopt" due to filters
;; Skipped "gethostname" due to filters
;; Skipped "sethostname" due to filters
;; Skipped "sethostid" due to filters
;; Skipped "getdomainname" due to filters
;; Skipped "setdomainname" due to filters
;; Skipped "vhangup" due to filters
;; Skipped "revoke" due to filters
;; Skipped "profil" due to filters
;; Skipped "acct" due to filters
;; Skipped "getusershell" due to filters
;; Skipped "endusershell" due to filters
;; Skipped "setusershell" due to filters
;; Skipped "daemon" due to filters
;; Skipped "chroot" due to filters
;; Skipped "getpass" due to filters
;; Skipped "fsync" due to filters
;; Skipped "gethostid" due to filters
;; Skipped "sync" due to filters
;; Skipped "getpagesize" due to filters
;; Skipped "getdtablesize" due to filters
;; Skipped "truncate" due to filters
;; Skipped "ftruncate" due to filters
;; Skipped "brk" due to filters
;; Skipped "sbrk" due to filters
;; Skipped "syscall" due to filters
;; Skipped "lockf" due to filters
;; Skipped "fdatasync" due to filters
;; Skipped "Byte" due to filters

;; "/usr/include/x86_64-linux-gnu/zconf.h:370:24"
(CFFI:DEFCTYPE |uInt| :UNSIGNED-INT)


;; "/usr/include/x86_64-linux-gnu/zconf.h:371:24"
(CFFI:DEFCTYPE |uLong| :UNSIGNED-LONG)

;; Skipped "Bytef" due to filters
;; Skipped "charf" due to filters
;; Skipped "intf" due to filters

;; "/usr/include/x86_64-linux-gnu/zconf.h:381:19"
(CFFI:DEFCTYPE |uIntf| |uInt|)


;; "/usr/include/x86_64-linux-gnu/zconf.h:382:19"
(CFFI:DEFCTYPE |uLongf| |uLong|)

;; Skipped "voidpc" due to filters

;; "/usr/include/x86_64-linux-gnu/zconf.h:386:24"
(CFFI:DEFCTYPE |voidpf| (:POINTER :VOID))


;; "/usr/include/x86_64-linux-gnu/zconf.h:387:24"
(CFFI:DEFCTYPE |voidp| (:POINTER :VOID))

;; Skipped "z_crc_t" due to filters
;; Skipped "u_char" due to filters
;; Skipped "u_short" due to filters
;; Skipped "u_int" due to filters
;; Skipped "u_long" due to filters
;; Skipped "quad_t" due to filters
;; Skipped "u_quad_t" due to filters
;; Skipped "fsid_t" due to filters
;; Skipped "loff_t" due to filters
;; Skipped "ino_t" due to filters
;; Skipped "dev_t" due to filters
;; Skipped "mode_t" due to filters
;; Skipped "nlink_t" due to filters
;; Skipped "id_t" due to filters
;; Skipped "daddr_t" due to filters
;; Skipped "caddr_t" due to filters
;; Skipped "key_t" due to filters
;; Skipped "clock_t" due to filters
;; Skipped "time_t" due to filters
;; Skipped "clockid_t" due to filters
;; Skipped "timer_t" due to filters
;; Skipped "ulong" due to filters
;; Skipped "ushort" due to filters
;; Skipped "uint" due to filters
;; Skipped "int8_t" due to filters
;; Skipped "int16_t" due to filters
;; Skipped "int32_t" due to filters
;; Skipped "int64_t" due to filters
;; Skipped "u_int8_t" due to filters
;; Skipped "u_int16_t" due to filters
;; Skipped "u_int32_t" due to filters
;; Skipped "u_int64_t" due to filters
;; Skipped "register_t" due to filters
;; Skipped "__sig_atomic_t" due to filters
;; Skipped "__sigset_t" due to filters
;; Skipped "sigset_t" due to filters
;; Skipped "timespec" due to filters
;; Skipped "timeval" due to filters
;; Skipped "suseconds_t" due to filters
;; Skipped "__fd_mask" due to filters
;; Skipped "fd_set" due to filters
;; Skipped "fd_mask" due to filters
;; Skipped "select" due to filters
;; Skipped "pselect" due to filters
;; Skipped "gnu_dev_major" due to filters
;; Skipped "gnu_dev_minor" due to filters
;; Skipped "gnu_dev_makedev" due to filters
;; Skipped "blksize_t" due to filters
;; Skipped "blkcnt_t" due to filters
;; Skipped "fsblkcnt_t" due to filters
;; Skipped "fsfilcnt_t" due to filters
;; Skipped "pthread_t" due to filters
;; Skipped "pthread_attr_t" due to filters
;; Skipped "pthread_attr_t" due to filters
;; Skipped "__pthread_internal_list" due to filters
;; Skipped "__pthread_list_t" due to filters
;; Skipped "__pthread_mutex_s" due to filters
;; Skipped "pthread_mutex_t" due to filters
;; Skipped "pthread_mutexattr_t" due to filters
;; Skipped "pthread_cond_t" due to filters
;; Skipped "pthread_condattr_t" due to filters
;; Skipped "pthread_key_t" due to filters
;; Skipped "pthread_once_t" due to filters
;; Skipped "pthread_rwlock_t" due to filters
;; Skipped "pthread_rwlockattr_t" due to filters
;; Skipped "pthread_spinlock_t" due to filters
;; Skipped "pthread_barrier_t" due to filters
;; Skipped "pthread_barrierattr_t" due to filters
;; Skipped "va_list" due to filters
;; Skipped "__gnuc_va_list" due to filters

;; "/usr/include/zlib.h:80:18"
(CFFI:DEFCTYPE |alloc_func| FUNCTION-POINTER)


;; "/usr/include/zlib.h:81:18"
(CFFI:DEFCTYPE |free_func| FUNCTION-POINTER)


;; "/usr/include/zlib.h:83:8"
(CFFI:DEFCSTRUCT (|internal_state| :SIZE 0))


;; "/usr/include/zlib.h:85:16"
(CFFI:DEFCSTRUCT (|internal_state| :SIZE 0))

(CFFI:DEFCSTRUCT (|z_stream_s| :SIZE 112)
  (|next_in| (:POINTER :VOID) :OFFSET 0)
  (|avail_in| |uInt| :OFFSET 8)
  (|total_in| |uLong| :OFFSET 16)
  (|next_out| (:POINTER :VOID) :OFFSET 24)
  (|avail_out| |uInt| :OFFSET 32)
  (|total_out| |uLong| :OFFSET 40)
  (|msg| :STRING :OFFSET 48)
  (|state| (:POINTER (:STRUCT |internal_state|)) :OFFSET 56)
  (|zalloc| |alloc_func| :OFFSET 64)
  (|zfree| |free_func| :OFFSET 72)
  (|opaque| |voidpf| :OFFSET 80)
  (|data_type| :INT :OFFSET 88)
  (|adler| |uLong| :OFFSET 96)
  (|reserved| |uLong| :OFFSET 104))


;; "/usr/include/zlib.h:104:3"
(CFFI:DEFCTYPE |z_stream| (:STRUCT |z_stream_s|))


;; "/usr/include/zlib.h:106:23"
(CFFI:DEFCTYPE |z_streamp| (:POINTER |z_stream|))


;; "/usr/include/zlib.h:112:16"
(CFFI:DEFCSTRUCT (|gz_header_s| :SIZE 80)
  (|text| :INT :OFFSET 0)
  (|time| |uLong| :OFFSET 8)
  (|xflags| :INT :OFFSET 16)
  (|os| :INT :OFFSET 20)
  (|extra| (:POINTER :VOID) :OFFSET 24)
  (|extra_len| |uInt| :OFFSET 32)
  (|extra_max| |uInt| :OFFSET 36)
  (|name| (:POINTER :VOID) :OFFSET 40)
  (|name_max| |uInt| :OFFSET 48)
  (|comment| (:POINTER :VOID) :OFFSET 56)
  (|comm_max| |uInt| :OFFSET 64)
  (|hcrc| :INT :OFFSET 68)
  (|done| :INT :OFFSET 72))


;; "/usr/include/zlib.h:127:3"
(CFFI:DEFCTYPE |gz_header| (:STRUCT |gz_header_s|))


;; "/usr/include/zlib.h:129:24"
(CFFI:DEFCTYPE |gz_headerp| (:POINTER |gz_header|))


;; "/usr/include/zlib.h:216:30"
(CFFI:DEFCFUN ("zlibVersion" |zlibVersion|)
    :STRING)


;; "/usr/include/zlib.h:246:21"
(CFFI:DEFCFUN ("deflate" |deflate|)
    :INT
  (|strm| |z_streamp|)
  (|flush| :INT))


;; "/usr/include/zlib.h:353:21"
(CFFI:DEFCFUN ("deflateEnd" |deflateEnd|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:392:21"
(CFFI:DEFCFUN ("inflate" |inflate|)
    :INT
  (|strm| |z_streamp|)
  (|flush| :INT))


;; "/usr/include/zlib.h:508:21"
(CFFI:DEFCFUN ("inflateEnd" |inflateEnd|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:587:21"
(CFFI:DEFCFUN ("deflateSetDictionary" |deflateSetDictionary|)
    :INT
  (|strm| |z_streamp|)
  (|dictionary| (:POINTER :VOID))
  (|dictLength| |uInt|))


;; "/usr/include/zlib.h:631:21"
(CFFI:DEFCFUN ("deflateCopy" |deflateCopy|)
    :INT
  (|dest| |z_streamp|)
  (|source| |z_streamp|))


;; "/usr/include/zlib.h:649:21"
(CFFI:DEFCFUN ("deflateReset" |deflateReset|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:660:21"
(CFFI:DEFCFUN ("deflateParams" |deflateParams|)
    :INT
  (|strm| |z_streamp|)
  (|level| :INT)
  (|strategy| :INT))


;; "/usr/include/zlib.h:681:21"
(CFFI:DEFCFUN ("deflateTune" |deflateTune|)
    :INT
  (|strm| |z_streamp|)
  (|good_length| :INT)
  (|max_lazy| :INT)
  (|nice_length| :INT)
  (|max_chain| :INT))


;; "/usr/include/zlib.h:698:23"
(CFFI:DEFCFUN ("deflateBound" |deflateBound|)
    |uLong|
  (|strm| |z_streamp|)
  (|sourceLen| |uLong|))


;; "/usr/include/zlib.h:713:21"
(CFFI:DEFCFUN ("deflatePending" |deflatePending|)
    :INT
  (|strm| |z_streamp|)
  (|pending| (:POINTER :UNSIGNED-INT))
  (|bits| (:POINTER :INT)))


;; "/usr/include/zlib.h:728:21"
(CFFI:DEFCFUN ("deflatePrime" |deflatePrime|)
    :INT
  (|strm| |z_streamp|)
  (|bits| :INT)
  (|value| :INT))


;; "/usr/include/zlib.h:745:21"
(CFFI:DEFCFUN ("deflateSetHeader" |deflateSetHeader|)
    :INT
  (|strm| |z_streamp|)
  (|head| |gz_headerp|))


;; "/usr/include/zlib.h:819:21"
(CFFI:DEFCFUN ("inflateSetDictionary" |inflateSetDictionary|)
    :INT
  (|strm| |z_streamp|)
  (|dictionary| (:POINTER :VOID))
  (|dictLength| |uInt|))


;; "/usr/include/zlib.h:842:21"
(CFFI:DEFCFUN ("inflateGetDictionary" |inflateGetDictionary|)
    :INT
  (|strm| |z_streamp|)
  (|dictionary| (:POINTER :VOID))
  (|dictLength| (:POINTER |uInt|)))


;; "/usr/include/zlib.h:857:21"
(CFFI:DEFCFUN ("inflateSync" |inflateSync|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:876:21"
(CFFI:DEFCFUN ("inflateCopy" |inflateCopy|)
    :INT
  (|dest| |z_streamp|)
  (|source| |z_streamp|))


;; "/usr/include/zlib.h:892:21"
(CFFI:DEFCFUN ("inflateReset" |inflateReset|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:902:21"
(CFFI:DEFCFUN ("inflateReset2" |inflateReset2|)
    :INT
  (|strm| |z_streamp|)
  (|windowBits| :INT))


;; "/usr/include/zlib.h:914:21"
(CFFI:DEFCFUN ("inflatePrime" |inflatePrime|)
    :INT
  (|strm| |z_streamp|)
  (|bits| :INT)
  (|value| :INT))


;; "/usr/include/zlib.h:935:22"
(CFFI:DEFCFUN ("inflateMark" |inflateMark|)
    :LONG
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:963:21"
(CFFI:DEFCFUN ("inflateGetHeader" |inflateGetHeader|)
    :INT
  (|strm| |z_streamp|)
  (|head| |gz_headerp|))


;; "/usr/include/zlib.h:1025:20"
(CFFI:DEFCTYPE |in_func| FUNCTION-POINTER)


;; "/usr/include/zlib.h:1027:15"
(CFFI:DEFCTYPE |out_func| FUNCTION-POINTER)


;; "/usr/include/zlib.h:1029:21"
(CFFI:DEFCFUN ("inflateBack" |inflateBack|)
    :INT
  (|strm| |z_streamp|)
  (|in| |in_func|)
  (|in_desc| (:POINTER :VOID))
  (|out| |out_func|)
  (|out_desc| (:POINTER :VOID)))


;; "/usr/include/zlib.h:1099:21"
(CFFI:DEFCFUN ("inflateBackEnd" |inflateBackEnd|)
    :INT
  (|strm| |z_streamp|))


;; "/usr/include/zlib.h:1107:23"
(CFFI:DEFCFUN ("zlibCompileFlags" |zlibCompileFlags|)
    |uLong|)


;; "/usr/include/zlib.h:1160:21"
(CFFI:DEFCFUN ("compress" |compress|)
    :INT
  (|dest| (:POINTER :VOID))
  (|destLen| (:POINTER |uLongf|))
  (|source| (:POINTER :VOID))
  (|sourceLen| |uLong|))


;; "/usr/include/zlib.h:1174:21"
(CFFI:DEFCFUN ("compress2" |compress2|)
    :INT
  (|dest| (:POINTER :VOID))
  (|destLen| (:POINTER |uLongf|))
  (|source| (:POINTER :VOID))
  (|sourceLen| |uLong|)
  (|level| :INT))


;; "/usr/include/zlib.h:1190:23"
(CFFI:DEFCFUN ("compressBound" |compressBound|)
    |uLong|
  (|sourceLen| |uLong|))


;; "/usr/include/zlib.h:1197:21"
(CFFI:DEFCFUN ("uncompress" |uncompress|)
    :INT
  (|dest| (:POINTER :VOID))
  (|destLen| (:POINTER |uLongf|))
  (|source| (:POINTER :VOID))
  (|sourceLen| |uLong|))


;; "/usr/include/zlib.h:1224:16"
(CFFI:DEFCSTRUCT (|gzFile_s| :SIZE 0))


;; "/usr/include/zlib.h:1224:26"
(CFFI:DEFCSTRUCT (|gzFile_s| :SIZE 0))

(CFFI:DEFCTYPE |gzFile| (:POINTER (:STRUCT |gzFile_s|)))


;; "/usr/include/zlib.h:1264:24"
(CFFI:DEFCFUN ("gzdopen" |gzdopen|)
    |gzFile|
  (|fd| :INT)
  (|mode| :STRING))


;; "/usr/include/zlib.h:1287:21"
(CFFI:DEFCFUN ("gzbuffer" |gzbuffer|)
    :INT
  (|file| |gzFile|)
  (|size| :UNSIGNED-INT))


;; "/usr/include/zlib.h:1304:21"
(CFFI:DEFCFUN ("gzsetparams" |gzsetparams|)
    :INT
  (|file| |gzFile|)
  (|level| :INT)
  (|strategy| :INT))


;; "/usr/include/zlib.h:1313:21"
(CFFI:DEFCFUN ("gzread" |gzread|)
    :INT
  (|file| |gzFile|)
  (|buf| |voidp|)
  (|len| :UNSIGNED-INT))


;; "/usr/include/zlib.h:1341:21"
;; Skipping definition ((:TAG . "function") (:NAME . "gzwrite") (:LOCATION . "/usr/include/zlib.h:1341:21") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "file") (:TYPE (:TAG . "gzFile"))) ((:TAG . "parameter") (:NAME . "buf") (:TYPE (:TAG . "voidpc"))) ((:TAG . "parameter") (:NAME . "len") (:TYPE (:TAG . ":unsigned-int") (:BIT-SIZE . 32) (:BIT-ALIGNMENT . 32)))) (:RETURN-TYPE (:TAG . ":int") (:BIT-SIZE . 32) (:BIT-ALIGNMENT . 32))) because of missing type |voidpc|

;; "/usr/include/zlib.h:1349:23"
(CFFI:DEFCFUN ("gzprintf" |gzprintf|)
    :INT
  (|file| |gzFile|)
  (|format| :STRING)
  COMMON-LISP:&REST)


;; "/usr/include/zlib.h:1364:21"
(CFFI:DEFCFUN ("gzputs" |gzputs|)
    :INT
  (|file| |gzFile|)
  (|s| :STRING))


;; "/usr/include/zlib.h:1372:24"
(CFFI:DEFCFUN ("gzgets" |gzgets|)
    :STRING
  (|file| |gzFile|)
  (|buf| :STRING)
  (|len| :INT))


;; "/usr/include/zlib.h:1385:21"
(CFFI:DEFCFUN ("gzputc" |gzputc|)
    :INT
  (|file| |gzFile|)
  (|c| :INT))


;; "/usr/include/zlib.h:1391:21"
(CFFI:DEFCFUN ("gzgetc" |gzgetc|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1400:21"
(CFFI:DEFCFUN ("gzungetc" |gzungetc|)
    :INT
  (|c| :INT)
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1412:21"
(CFFI:DEFCFUN ("gzflush" |gzflush|)
    :INT
  (|file| |gzFile|)
  (|flush| :INT))


;; "/usr/include/zlib.h:1447:24"
(CFFI:DEFCFUN ("gzrewind" |gzrewind|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1475:21"
(CFFI:DEFCFUN ("gzeof" |gzeof|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1490:21"
(CFFI:DEFCFUN ("gzdirect" |gzdirect|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1511:24"
(CFFI:DEFCFUN ("gzclose" |gzclose|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1524:21"
(CFFI:DEFCFUN ("gzclose_r" |gzclose_r|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1525:21"
(CFFI:DEFCFUN ("gzclose_w" |gzclose_w|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1536:30"
(CFFI:DEFCFUN ("gzerror" |gzerror|)
    :STRING
  (|file| |gzFile|)
  (|errnum| (:POINTER :INT)))


;; "/usr/include/zlib.h:1552:22"
(CFFI:DEFCFUN ("gzclearerr" |gzclearerr|)
    :VOID
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1569:23"
(CFFI:DEFCFUN ("adler32" |adler32|)
    |uLong|
  (|adler| |uLong|)
  (|buf| (:POINTER :VOID))
  (|len| |uInt|))


;; "/usr/include/zlib.h:1600:23"
(CFFI:DEFCFUN ("crc32" |crc32|)
    |uLong|
  (|crc| |uLong|)
  (|buf| (:POINTER :VOID))
  (|len| |uInt|))


;; "/usr/include/zlib.h:1633:21"
(CFFI:DEFCFUN ("deflateInit_" |deflateInit_|)
    :INT
  (|strm| |z_streamp|)
  (|level| :INT)
  (|version| :STRING)
  (|stream_size| :INT))


;; "/usr/include/zlib.h:1635:21"
(CFFI:DEFCFUN ("inflateInit_" |inflateInit_|)
    :INT
  (|strm| |z_streamp|)
  (|version| :STRING)
  (|stream_size| :INT))


;; "/usr/include/zlib.h:1637:21"
(CFFI:DEFCFUN ("deflateInit2_" |deflateInit2_|)
    :INT
  (|strm| |z_streamp|)
  (|level| :INT)
  (|method| :INT)
  (|windowBits| :INT)
  (|memLevel| :INT)
  (|strategy| :INT)
  (|version| :STRING)
  (|stream_size| :INT))


;; "/usr/include/zlib.h:1641:21"
(CFFI:DEFCFUN ("inflateInit2_" |inflateInit2_|)
    :INT
  (|strm| |z_streamp|)
  (|windowBits| :INT)
  (|version| :STRING)
  (|stream_size| :INT))


;; "/usr/include/zlib.h:1643:21"
(CFFI:DEFCFUN ("inflateBackInit_" |inflateBackInit_|)
    :INT
  (|strm| |z_streamp|)
  (|windowBits| :INT)
  (|window| (:POINTER :UNSIGNED-CHAR))
  (|version| :STRING)
  (|stream_size| :INT))


;; "/usr/include/zlib.h:1670:8"
;; skipping field due to missing type ((:TAG . "off_t")), full json entry: ((:TAG . "field") (:NAME . "pos") (:BIT-OFFSET . 128) (:BIT-SIZE . 64) (:BIT-ALIGNMENT . 64) (:TYPE (:TAG . "off_t")))
(CFFI:DEFCSTRUCT (|gzFile_s| :SIZE 24)
  (|have| :UNSIGNED-INT :OFFSET 0)
  (|next| (:POINTER :UNSIGNED-CHAR) :OFFSET 8))


;; "/usr/include/zlib.h:1675:21"
(CFFI:DEFCFUN ("gzgetc_" |gzgetc_|)
    :INT
  (|file| |gzFile|))


;; "/usr/include/zlib.h:1725:27"
(CFFI:DEFCFUN ("gzopen" |gzopen|)
    |gzFile|
  (ARG1 :STRING)
  (ARG2 :STRING))


;; "/usr/include/zlib.h:1726:28"
;; Skipping definition ((:TAG . "function") (:NAME . "gzseek") (:LOCATION . "/usr/include/zlib.h:1726:28") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "gzFile"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "off_t"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . ":int") (:BIT-SIZE . 32) (:BIT-ALIGNMENT . 32)))) (:RETURN-TYPE (:TAG . "off_t"))) because of missing type |off_t|

;; "/usr/include/zlib.h:1727:28"
;; Skipping definition ((:TAG . "function") (:NAME . "gztell") (:LOCATION . "/usr/include/zlib.h:1727:28") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "gzFile")))) (:RETURN-TYPE (:TAG . "off_t"))) because of missing type |off_t|

;; "/usr/include/zlib.h:1728:28"
;; Skipping definition ((:TAG . "function") (:NAME . "gzoffset") (:LOCATION . "/usr/include/zlib.h:1728:28") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "gzFile")))) (:RETURN-TYPE (:TAG . "off_t"))) because of missing type |off_t|

;; "/usr/include/zlib.h:1729:26"
;; Skipping definition ((:TAG . "function") (:NAME . "adler32_combine") (:LOCATION . "/usr/include/zlib.h:1729:26") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "uLong"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "uLong"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "off_t")))) (:RETURN-TYPE (:TAG . "uLong"))) because of missing type |off_t|

;; "/usr/include/zlib.h:1730:26"
;; Skipping definition ((:TAG . "function") (:NAME . "crc32_combine") (:LOCATION . "/usr/include/zlib.h:1730:26") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "uLong"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "uLong"))) ((:TAG . "parameter") (:NAME . "") (:TYPE (:TAG . "off_t")))) (:RETURN-TYPE (:TAG . "uLong"))) because of missing type |off_t|

;; "/usr/include/zlib.h:1742:12"
(CFFI:DEFCSTRUCT (|internal_state| :SIZE 4)
  (|dummy| :INT :OFFSET 0))


;; "/usr/include/zlib.h:1746:32"
(CFFI:DEFCFUN ("zError" |zError|)
    :STRING
  (ARG1 :INT))


;; "/usr/include/zlib.h:1747:32"
(CFFI:DEFCFUN ("inflateSyncPoint" |inflateSyncPoint|)
    :INT
  (ARG1 |z_streamp|))


;; "/usr/include/zlib.h:1748:37"
(CFFI:DEFCFUN ("get_crc_table" |get_crc_table|)
    (:POINTER :VOID))


;; "/usr/include/zlib.h:1749:32"
(CFFI:DEFCFUN ("inflateUndermine" |inflateUndermine|)
    :INT
  (ARG1 |z_streamp|)
  (ARG2 :INT))


;; "/usr/include/zlib.h:1750:32"
(CFFI:DEFCFUN ("inflateResetKeep" |inflateResetKeep|)
    :INT
  (ARG1 |z_streamp|))


;; "/usr/include/zlib.h:1751:32"
(CFFI:DEFCFUN ("deflateResetKeep" |deflateResetKeep|)
    :INT
  (ARG1 |z_streamp|))


;; "/usr/include/zlib.h:1758:34"
;; Skipping definition ((:TAG . "function") (:NAME . "gzvprintf") (:LOCATION . "/usr/include/zlib.h:1758:34") (:VARIADIC) (:INLINE) (:STORAGE-CLASS . "extern") (:PARAMETERS ((:TAG . "parameter") (:NAME . "file") (:TYPE (:TAG . "gzFile"))) ((:TAG . "parameter") (:NAME . "format") (:TYPE (:TAG . ":pointer") (:TYPE (:TAG . ":char") (:BIT-SIZE . 8) (:BIT-ALIGNMENT . 8)))) ((:TAG . "parameter") (:NAME . "va") (:TYPE (:TAG . "va_list")))) (:RETURN-TYPE (:TAG . ":int") (:BIT-SIZE . 32) (:BIT-ALIGNMENT . 32))) because of missing type |va_list|
;; Skipped "__GID_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFF32_LIBS" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS" due to filters
;; Skipped "__UID_T_TYPE" due to filters
;; Skipped "__INO64_T_TYPE" due to filters
;; Skipped "_XOPEN_XCU_VERSION" due to filters
;; Skipped "__INO_T_TYPE" due to filters
;; Skipped "_XOPEN_XPG2" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS" due to filters
;; Skipped "__NLINK_T_TYPE" due to filters
;; Skipped "_XOPEN_XPG3" due to filters
;; Skipped "_XOPEN_UNIX" due to filters
;; Skipped "_XOPEN_XPG4" due to filters
;; Skipped "_XOPEN_CRYPT" due to filters
;; Skipped "_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFF32_LDFLAGS" due to filters
;; Skipped "__FSWORD_T_TYPE" due to filters
;; Skipped "_XOPEN_ENH_I18N" due to filters
;; Skipped "__OFF_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS" due to filters
;; Skipped "__ULONG32_TYPE" due to filters
;; Skipped "__MODE_T_TYPE" due to filters
;; Skipped "__SLONG32_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFF32_CFLAGS" due to filters
;; Skipped "__U64_TYPE" due to filters
;; Skipped "__OFF64_T_TYPE" due to filters
;; Skipped "__S64_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS" due to filters
;; Skipped "_CS_POSIX_V6_LPBIG_OFFBIG_LIBS" due to filters
;; Skipped "__SYSCALL_SLONG_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_LP64_OFF64_CFLAGS" due to filters
;; Skipped "_BITS_TYPESIZES_H" due to filters
;; Skipped "__DEV_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_LP64_OFF64_LDFLAGS" due to filters
;; Skipped "__SYSCALL_ULONG_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_LP64_OFF64_LIBS" due to filters
;; Skipped "_CS_V7_ENV" due to filters
;; Skipped "_CS_V6_ENV" due to filters
;; Skipped "_CS_POSIX_V6_LP64_OFF64_LINTFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_LPBIG_OFFBIG_LIBS" due to filters
;; Skipped "_CS_POSIX_V7_LP64_OFF64_LIBS" due to filters
;; Skipped "__RLIM_T_TYPE" due to filters
;; Skipped "__PID_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_LP64_OFF64_LDFLAGS" due to filters
;; Skipped "__BLKCNT_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_LP64_OFF64_LINTFLAGS" due to filters
;; Skipped "__RLIM64_T_TYPE" due to filters
;; Skipped "__FSBLKCNT_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFFBIG_LIBS" due to filters
;; Skipped "__BLKCNT64_T_TYPE" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_LP64_OFF64_CFLAGS" due to filters
;; Skipped "_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS" due to filters
;; Skipped "STDOUT_FILENO" due to filters
;; Skipped "_POSIX_THREAD_PRIO_PROTECT" due to filters
;; Skipped "STDERR_FILENO" due to filters
;; Skipped "_BITS_TYPES_H" due to filters
;; Skipped "_POSIX_THREAD_ROBUST_PRIO_PROTECT" due to filters
;; Skipped "__blksize_t_defined" due to filters
;; Skipped "__blkcnt_t_defined" due to filters
;; Skipped "_POSIX_THREAD_ROBUST_PRIO_INHERIT" due to filters
;; Skipped "_POSIX_REALTIME_SIGNALS" due to filters
;; Skipped "__fsblkcnt_t_defined" due to filters
;; Skipped "_POSIX_SEMAPHORES" due to filters
;; Skipped "_POSIX_ASYNC_IO" due to filters
;; Skipped "__fsfilcnt_t_defined" due to filters
;; Skipped "_POSIX_ASYNCHRONOUS_IO" due to filters
;; Skipped "_XBS5_LP64_OFF64" due to filters
;; Skipped "_POSIX_THREADS" due to filters
;; Skipped "_XOPEN_SHM" due to filters
;; Skipped "__ILP32_OFF32_CFLAGS" due to filters
;; Skipped "_BITS_PTHREADTYPES_H" due to filters
;; Skipped "__SIZEOF_PTHREAD_ATTR_T" due to filters
;; Skipped "_POSIX_THREAD_SAFE_FUNCTIONS" due to filters
;; Skipped "__ILP32_OFF32_LDFLAGS" due to filters
;; Skipped "__SIZEOF_PTHREAD_MUTEX_T" due to filters
;; Skipped "_POSIX_REENTRANT_FUNCTIONS" due to filters
;; Skipped "__ILP32_OFFBIG_CFLAGS" due to filters
;; Skipped "_POSIX_THREAD_ATTR_STACKSIZE" due to filters
;; Skipped "__SIZEOF_PTHREAD_MUTEXATTR_T" due to filters
;; Skipped "__ILP32_OFFBIG_LDFLAGS" due to filters
;; Skipped "__SIZEOF_PTHREAD_COND_T" due to filters
;; Skipped "_POSIX_THREAD_PRIORITY_SCHEDULING" due to filters
;; Skipped "__LP64_OFF64_CFLAGS" due to filters
;; Skipped "_POSIX_THREAD_PRIO_INHERIT" due to filters
;; Skipped "__LP64_OFF64_LDFLAGS" due to filters
;; Skipped "_POSIX_THREAD_ATTR_STACKADDR" due to filters
;; Skipped "__SIZEOF_PTHREAD_CONDATTR_T" due to filters
;; Skipped "STDIN_FILENO" due to filters
;; Skipped "_POSIX_MEMLOCK_RANGE" due to filters
;; Skipped "_SC_HOST_NAME_MAX" due to filters
;; Skipped "__U16_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS" due to filters
;; Skipped "_POSIX_MEMLOCK" due to filters
;; Skipped "_SC_V6_LPBIG_OFFBIG" due to filters
;; Skipped "__S32_TYPE" due to filters
;; Skipped "_SC_TRACE_EVENT_FILTER" due to filters
;; Skipped "_POSIX_CHOWN_RESTRICTED" due to filters
;; Skipped "__U32_TYPE" due to filters
;; Skipped "_SC_TRACE" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFFBIG_LIBS" due to filters
;; Skipped "_POSIX_MEMORY_PROTECTION" due to filters
;; Skipped "_POSIX_NO_TRUNC" due to filters
;; Skipped "__SQUAD_TYPE" due to filters
;; Skipped "__SLONGWORD_TYPE" due to filters
;; Skipped "__ULONGWORD_TYPE" due to filters
;; Skipped "_POSIX_VDISABLE" due to filters
;; Skipped "__UQUAD_TYPE" due to filters
;; Skipped "_SC_TRACE_INHERIT" due to filters
;; Skipped "_SC_TRACE_LOG" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFF32_LIBS" due to filters
;; Skipped "_XOPEN_REALTIME_THREADS" due to filters
;; Skipped "__SWORD_TYPE" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS" due to filters
;; Skipped "_SC_LEVEL1_ICACHE_ASSOC" due to filters
;; Skipped "_XOPEN_REALTIME" due to filters
;; Skipped "__UWORD_TYPE" due to filters
;; Skipped "_SC_LEVEL1_ICACHE_SIZE" due to filters
;; Skipped "_CS_XBS5_LPBIG_OFFBIG_LIBS" due to filters
;; Skipped "_BITS_POSIX_OPT_H" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS" due to filters
;; Skipped "_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS" due to filters
;; Skipped "_XOPEN_LEGACY" due to filters
;; Skipped "_SYS_SYSMACROS_H" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFF32_LDFLAGS" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFF32_CFLAGS" due to filters
;; Skipped "_POSIX_SAVED_IDS" due to filters
;; Skipped "_POSIX_JOB_CONTROL" due to filters
;; Skipped "_POSIX_SYNCHRONIZED_IO" due to filters
;; Skipped "_CS_XBS5_LP64_OFF64_LIBS" due to filters
;; Skipped "_POSIX_PRIORITY_SCHEDULING" due to filters
;; Skipped "_CS_XBS5_LP64_OFF64_LINTFLAGS" due to filters
;; Skipped "_POSIX_MAPPED_FILES" due to filters
;; Skipped "_CS_XBS5_LPBIG_OFFBIG_CFLAGS" due to filters
;; Skipped "_POSIX_FSYNC" due to filters
;; Skipped "__S16_TYPE" due to filters
;; Skipped "_CS_XBS5_LPBIG_OFFBIG_LDFLAGS" due to filters
;; Skipped "_SC_LEVEL3_CACHE_LINESIZE" due to filters
;; Skipped "_SC_LEVEL4_CACHE_SIZE" due to filters
;; Skipped "_POSIX_SPORADIC_SERVER" due to filters
;; Skipped "_SC_LEVEL3_CACHE_ASSOC" due to filters
;; Skipped "__int8_t_defined" due to filters
;; Skipped "_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS" due to filters
;; Skipped "_SC_IPV6" due to filters
;; Skipped "_SC_RAW_SOCKETS" due to filters
;; Skipped "_SC_V7_ILP32_OFF32" due to filters
;; Skipped "_SC_LEVEL4_CACHE_ASSOC" due to filters
;; Skipped "_SC_LEVEL4_CACHE_LINESIZE" due to filters
;; Skipped "_POSIX_MONOTONIC_CLOCK" due to filters
;; Skipped "_SC_LEVEL1_DCACHE_ASSOC" due to filters
;; Skipped "_POSIX_CLOCK_SELECTION" due to filters
;; Skipped "_SC_LEVEL1_DCACHE_LINESIZE" due to filters
;; Skipped "_SC_LEVEL1_ICACHE_LINESIZE" due to filters
;; Skipped "_POSIX_MESSAGE_PASSING" due to filters
;; Skipped "_POSIX_THREAD_PROCESS_SHARED" due to filters
;; Skipped "_SC_LEVEL1_DCACHE_SIZE" due to filters
;; Skipped "__FD_SETSIZE" due to filters
;; Skipped "_ENDIAN_H" due to filters
;; Skipped "_POSIX_RAW_SOCKETS" due to filters
;; Skipped "_SC_LEVEL2_CACHE_LINESIZE" due to filters
;; Skipped "__LITTLE_ENDIAN" due to filters
;; Skipped "__BIT_TYPES_DEFINED__" due to filters
;; Skipped "_POSIX2_CHAR_TERM" due to filters
;; Skipped "_POSIX_ADVISORY_INFO" due to filters
;; Skipped "_SC_LEVEL3_CACHE_SIZE" due to filters
;; Skipped "_SC_LEVEL2_CACHE_SIZE" due to filters
;; Skipped "_POSIX_IPV6" due to filters
;; Skipped "_SC_LEVEL2_CACHE_ASSOC" due to filters
;; Skipped "_POSIX_READER_WRITER_LOCKS" due to filters
;; Skipped "_POSIX_SHELL" due to filters
;; Skipped "__FSID_T_TYPE" due to filters
;; Skipped "_SC_THREAD_ROBUST_PRIO_INHERIT" due to filters
;; Skipped "_POSIX_TIMEOUTS" due to filters
;; Skipped "__BLKSIZE_T_TYPE" due to filters
;; Skipped "_POSIX_THREAD_CPUTIME" due to filters
;; Skipped "_POSIX_REGEXP" due to filters
;; Skipped "__TIMER_T_TYPE" due to filters
;; Skipped "__CLOCKID_T_TYPE" due to filters
;; Skipped "__KEY_T_TYPE" due to filters
;; Skipped "_SC_TRACE_USER_EVENT_MAX" due to filters
;; Skipped "_SC_XOPEN_STREAMS" due to filters
;; Skipped "__INO_T_MATCHES_INO64_T" due to filters
;; Skipped "_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "_POSIX_BARRIERS" due to filters
;; Skipped "__OFF_T_MATCHES_OFF64_T" due to filters
;; Skipped "_POSIX_TIMERS" due to filters
;; Skipped "__SSIZE_T_TYPE" due to filters
;; Skipped "__attribute_pure__" due to filters
;; Skipped "_POSIX_SPIN_LOCKS" due to filters
;; Skipped "_CS_PATH" due to filters
;; Skipped "_CS_V6_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "_POSIX_SPAWN" due to filters
;; Skipped "_LFS64_ASYNCHRONOUS_IO" due to filters
;; Skipped "__CLOCK_T_TYPE" due to filters
;; Skipped "_LFS_LARGEFILE" due to filters
;; Skipped "_SC_SS_REPL_MAX" due to filters
;; Skipped "__ID_T_TYPE" due to filters
;; Skipped "_SC_V7_LPBIG_OFFBIG" due to filters
;; Skipped "_LFS_ASYNCHRONOUS_IO" due to filters
;; Skipped "__FSFILCNT64_T_TYPE" due to filters
;; Skipped "_SC_V7_ILP32_OFFBIG" due to filters
;; Skipped "_POSIX_PRIORITIZED_IO" due to filters
;; Skipped "__FSFILCNT_T_TYPE" due to filters
;; Skipped "_POSIX_SHARED_MEMORY_OBJECTS" due to filters
;; Skipped "__DADDR_T_TYPE" due to filters
;; Skipped "_SC_TRACE_SYS_MAX" due to filters
;; Skipped "_SC_V7_LP64_OFF64" due to filters
;; Skipped "_POSIX_CPUTIME" due to filters
;; Skipped "__SUSECONDS_T_TYPE" due to filters
;; Skipped "_LFS64_LARGEFILE" due to filters
;; Skipped "__USECONDS_T_TYPE" due to filters
;; Skipped "_SC_TRACE_EVENT_NAME_MAX" due to filters
;; Skipped "_LFS64_STDIO" due to filters
;; Skipped "__TIME_T_TYPE" due to filters
;; Skipped "_SC_TRACE_NAME_MAX" due to filters
;; Skipped "_DEFAULT_SOURCE" due to filters
;; Skipped "_CS_GNU_LIBC_VERSION" due to filters
;; Skipped "_CS_LFS64_LIBS" due to filters
;; Skipped "_CS_LFS64_CFLAGS" due to filters
;; Skipped "_CS_LFS64_LDFLAGS" due to filters
;; Skipped "_SC_THREAD_ROBUST_PRIO_PROTECT" due to filters
;; Skipped "_CS_LFS_LINTFLAGS" due to filters
;; Skipped "_POSIX_SOURCE" due to filters
;; Skipped "_CS_LFS_LIBS" due to filters
;; Skipped "_POSIX_C_SOURCE" due to filters
;; Skipped "__flexarr" due to filters
;; Skipped "__fortify_function" due to filters
;; Skipped "_CS_XBS5_ILP32_OFF32_LDFLAGS" due to filters
;; Skipped "__extern_always_inline" due to filters
;; Skipped "__FSBLKCNT64_T_TYPE" due to filters
;; Skipped "_CS_XBS5_ILP32_OFF32_CFLAGS" due to filters
;; Skipped "__attribute_artificial__" due to filters
;; Skipped "_CS_LFS64_LINTFLAGS" due to filters
;; Skipped "_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "__USE_POSIX_IMPLICITLY" due to filters
;; Skipped "_ATFILE_SOURCE" due to filters
;; Skipped "__attribute_malloc__" due to filters
;; Skipped "_CS_GNU_LIBPTHREAD_VERSION" due to filters
;; Skipped "_CS_LFS_LDFLAGS" due to filters
;; Skipped "_CS_V5_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "_CS_LFS_CFLAGS" due to filters
;; Skipped "_BSD_SOURCE" due to filters
;; Skipped "_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "_SVID_SOURCE" due to filters
;; Skipped "_CS_V7_WIDTH_RESTRICTED_ENVS" due to filters
;; Skipped "__BEGIN_DECLS" due to filters
;; Skipped "__FLOAT_WORD_ORDER" due to filters
;; Skipped "__END_DECLS" due to filters
;; Skipped "__BYTE_ORDER" due to filters
;; Skipped "__PDP_ENDIAN" due to filters
;; Skipped "__BEGIN_NAMESPACE_STD" due to filters
;; Skipped "__BIG_ENDIAN" due to filters
;; Skipped "__END_NAMESPACE_STD" due to filters
;; Skipped "_CS_XBS5_LP64_OFF64_LDFLAGS" due to filters
;; Skipped "PDP_ENDIAN" due to filters
;; Skipped "BYTE_ORDER" due to filters
;; Skipped "BIG_ENDIAN" due to filters
;; Skipped "__ptr_t" due to filters
;; Skipped "__long_double_t" due to filters
;; Skipped "LITTLE_ENDIAN" due to filters
;; Skipped "_CS_XBS5_ILP32_OFFBIG_LDFLAGS" due to filters
;; Skipped "_CS_XBS5_ILP32_OFFBIG_CFLAGS" due to filters
;; Skipped "_CS_XBS5_ILP32_OFF32_LINTFLAGS" due to filters
;; Skipped "_CS_XBS5_ILP32_OFF32_LIBS" due to filters
;; Skipped "_CS_XBS5_LP64_OFF64_CFLAGS" due to filters
;; Skipped "_CS_XBS5_ILP32_OFFBIG_LINTFLAGS" due to filters
;; Skipped "__BEGIN_NAMESPACE_C99" due to filters
;; Skipped "_CS_XBS5_ILP32_OFFBIG_LIBS" due to filters
;; Skipped "_BITS_BYTESWAP_H" due to filters
;; Skipped "__END_NAMESPACE_C99" due to filters
;; Skipped "_UNISTD_H" due to filters
;; Skipped "__GLIBC_MINOR__" due to filters
;; Skipped "__GLIBC__" due to filters
;; Skipped "__GNU_LIBRARY__" due to filters
;; Skipped "__STDC_NO_THREADS__" due to filters
;; Skipped "__USE_ISOC95" due to filters
;; Skipped "__USE_ISOC11" due to filters
;; Skipped "__USE_ISOC99" due to filters
;; Skipped "_SYS_CDEFS_H" due to filters
;; Skipped "_FEATURES_H" due to filters
;; Skipped "__USE_POSIX199309" due to filters
;; Skipped "__USE_POSIX2" due to filters
;; Skipped "__THROW" due to filters
;; Skipped "__LEAF_ATTR" due to filters
;; Skipped "__USE_POSIX" due to filters
;; Skipped "__LEAF" due to filters
;; Skipped "__USE_POSIX199506" due to filters
;; Skipped "__THROWNL" due to filters
;; Skipped "__USE_XOPEN2K8" due to filters
;; Skipped "__USE_XOPEN2K" due to filters
;; Skipped "__USE_SVID" due to filters
;; Skipped "__USE_BSD" due to filters
;; Skipped "_SYS_SELECT_H" due to filters
;; Skipped "_STDC_PREDEF_H" due to filters
;; Skipped "__USE_ATFILE" due to filters
;; Skipped "__USE_MISC" due to filters
;; Skipped "__STDC_ISO_10646__" due to filters
;; Skipped "__FD_ZERO_STOS" due to filters
;; Skipped "__STDC_IEC_559_COMPLEX__" due to filters
;; Skipped "__KERNEL_STRICT_NAMES" due to filters
;; Skipped "__STDC_IEC_559__" due to filters
;; Skipped "__USE_FORTIFY_LEVEL" due to filters
;; Skipped "__gid_t_defined" due to filters
;; Skipped "__uid_t_defined" due to filters
;; Skipped "_SIZE_T" due to filters
;; Skipped "NULL" due to filters
;; Skipped "__ssize_t_defined" due to filters
;; Skipped "__attribute_noinline__" due to filters
;; Skipped "__attribute_deprecated__" due to filters
;; Skipped "__attribute_const__" due to filters
;; Skipped "__attribute_used__" due to filters
;; Skipped "__extern_inline" due to filters
;; Skipped "__wur" due to filters
;; Skipped "__always_inline" due to filters
;; Skipped "__attribute_warn_unused_result__" due to filters
;; Skipped "F_OK" due to filters
;; Skipped "X_OK" due to filters
;; Skipped "__socklen_t_defined" due to filters
;; Skipped "R_OK" due to filters
;; Skipped "W_OK" due to filters
;; Skipped "__WORDSIZE_TIME64_COMPAT32" due to filters
;; Skipped "__SYSCALL_WORDSIZE" due to filters
;; Skipped "__pid_t_defined" due to filters
;; Skipped "__WORDSIZE" due to filters
;; Skipped "__intptr_t_defined" due to filters
;; Skipped "__off_t_defined" due to filters
;; Skipped "__restrict_arr" due to filters
;; Skipped "__useconds_t_defined" due to filters
;; Skipped "__stub_stty" due to filters
;; Skipped "PTHREAD_KEYS_MAX" due to filters
;; Skipped "__stub_sigreturn" due to filters
;; Skipped "__stub_sstk" due to filters
;; Skipped "__time_t_defined" due to filters
;; Skipped "__stub_setlogin" due to filters
;; Skipped "__clockid_t_defined" due to filters
;; Skipped "_POSIX_THREAD_DESTRUCTOR_ITERATIONS" due to filters
;; Skipped "__stub_revoke" due to filters
;; Skipped "__stub_putmsg" due to filters
;; Skipped "_POSIX_THREAD_THREADS_MAX" due to filters
;; Skipped "PTHREAD_DESTRUCTOR_ITERATIONS" due to filters
;; Skipped "__stub_lchmod" due to filters
;; Skipped "__timer_t_defined" due to filters
;; Skipped "AIO_PRIO_DELTA_MAX" due to filters
;; Skipped "__stub_gtty" due to filters
;; Skipped "__stub_getmsg" due to filters
;; Skipped "__timespec_defined" due to filters
;; Skipped "SEEK_END" due to filters
;; Skipped "__stub_fattach" due to filters
;; Skipped "__stub_fdetach" due to filters
;; Skipped "__stub_fchflags" due to filters
;; Skipped "__stub_chflags" due to filters
;; Skipped "SEEK_CUR" due to filters
;; Skipped "L_INCR" due to filters
;; Skipped "L_XTND" due to filters
;; Skipped "__stub_bdflush" due to filters
;; Skipped "L_SET" due to filters
;; Skipped "NAME_MAX" due to filters
;; Skipped "MAX_INPUT" due to filters
;; Skipped "PIPE_BUF" due to filters
;; Skipped "PATH_MAX" due to filters
;; Skipped "XATTR_NAME_MAX" due to filters
;; Skipped "XATTR_LIST_MAX" due to filters
;; Skipped "XATTR_SIZE_MAX" due to filters
;; Skipped "SEEK_SET" due to filters
;; Skipped "RTSIG_MAX" due to filters
;; Skipped "_POSIX_THREAD_KEYS_MAX" due to filters
;; Skipped "__clock_t_defined" due to filters
;; Skipped "__mode_t_defined" due to filters
;; Skipped "__key_t_defined" due to filters
;; Skipped "__nlink_t_defined" due to filters
;; Skipped "__need_clockid_t" due to filters
;; Skipped "__id_t_defined" due to filters
;; Skipped "__daddr_t_defined" due to filters
;; Skipped "_XOPEN_VERSION" due to filters
;; Skipped "_POSIX2_LOCALEDEF" due to filters
;; Skipped "_POSIX2_SW_DEV" due to filters
;; Skipped "_POSIX2_C_DEV" due to filters
;; Skipped "_POSIX2_C_BIND" due to filters
;; Skipped "__ino_t_defined" due to filters
;; Skipped "_POSIX2_VERSION" due to filters
;; Skipped "__POSIX2_THIS_VERSION" due to filters
;; Skipped "_POSIX_VERSION" due to filters
;; Skipped "__dev_t_defined" due to filters
;; Skipped "_POSIX_OPEN_MAX" due to filters
;; Skipped "EXPR_NEST_MAX" due to filters
;; Skipped "_SC_NGROUPS_MAX" due to filters
;; Skipped "_SC_CHILD_MAX" due to filters
;; Skipped "_POSIX_NGROUPS_MAX" due to filters
;; Skipped "_SC_DEVICE_IO" due to filters
;; Skipped "_SC_CLK_TCK" due to filters
;; Skipped "_SC_ARG_MAX" due to filters
;; Skipped "_SC_THREAD_CPUTIME" due to filters
;; Skipped "_SC_DEVICE_SPECIFIC" due to filters
;; Skipped "BC_STRING_MAX" due to filters
;; Skipped "_POSIX_NAME_MAX" due to filters
;; Skipped "_PC_2_SYMLINKS" due to filters
;; Skipped "_SC_DEVICE_SPECIFIC_R" due to filters
;; Skipped "_POSIX_MQ_PRIO_MAX" due to filters
;; Skipped "BC_DIM_MAX" due to filters
;; Skipped "_SC_JOB_CONTROL" due to filters
;; Skipped "_POSIX_MQ_OPEN_MAX" due to filters
;; Skipped "_SC_C_LANG_SUPPORT" due to filters
;; Skipped "BC_BASE_MAX" due to filters
;; Skipped "_SC_TZNAME_MAX" due to filters
;; Skipped "_POSIX_MAX_INPUT" due to filters
;; Skipped "_SC_C_LANG_SUPPORT_R" due to filters

;; "/usr/include/zlib.h:181:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_VERSION_ERROR -6)

;; Skipped "_POSIX2_CHARCLASS_NAME_MAX" due to filters
;; Skipped "_SC_STREAM_MAX" due to filters
;; Skipped "_SC_CLOCK_SELECTION" due to filters
;; Skipped "_POSIX2_RE_DUP_MAX" due to filters
;; Skipped "_POSIX_MAX_CANON" due to filters
;; Skipped "_SC_OPEN_MAX" due to filters
;; Skipped "_SC_CPUTIME" due to filters
;; Skipped "_SC_FILE_LOCKING" due to filters
;; Skipped "_SC_TIMERS" due to filters
;; Skipped "_POSIX_SSIZE_MAX" due to filters
;; Skipped "COLL_WEIGHTS_MAX" due to filters
;; Skipped "_POSIX_LOGIN_NAME_MAX" due to filters
;; Skipped "_SC_PRIORITY_SCHEDULING" due to filters
;; Skipped "_SC_FILE_SYSTEM" due to filters

;; "/usr/include/zlib.h:188:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_BEST_COMPRESSION 9)

;; Skipped "_POSIX_SIGQUEUE_MAX" due to filters
;; Skipped "_SC_REALTIME_SIGNALS" due to filters
;; Skipped "_SC_MONOTONIC_CLOCK" due to filters
;; Skipped "BC_SCALE_MAX" due to filters
;; Skipped "_POSIX_SEM_VALUE_MAX" due to filters
;; Skipped "_SC_SAVED_IDS" due to filters
;; Skipped "_SC_MULTI_PROCESS" due to filters
;; Skipped "_SYS_TYPES_H" due to filters
;; Skipped "_POSIX_SEM_NSEMS_MAX" due to filters
;; Skipped "_POSIX_RTSIG_MAX" due to filters
;; Skipped "_SC_MAPPED_FILES" due to filters
;; Skipped "_SC_FD_MGMT" due to filters
;; Skipped "_SC_FIFO" due to filters
;; Skipped "_SC_SYNCHRONIZED_IO" due to filters
;; Skipped "_SC_FSYNC" due to filters
;; Skipped "Z_HAVE_UNISTD_H" due to filters
;; Skipped "_SC_PIPE" due to filters
;; Skipped "_SC_PRIORITIZED_IO" due to filters
;; Skipped "_POSIX_PIPE_BUF" due to filters
;; Skipped "_POSIX_RE_DUP_MAX" due to filters
;; Skipped "_SC_FILE_ATTRIBUTES" due to filters
;; Skipped "_SC_ASYNCHRONOUS_IO" due to filters
;; Skipped "_POSIX_PATH_MAX" due to filters
;; Skipped "LINE_MAX" due to filters
;; Skipped "_SC_MESSAGE_PASSING" due to filters
;; Skipped "_SC_REGEX_VERSION" due to filters
;; Skipped "SSIZE_MAX" due to filters
;; Skipped "_SC_SHELL" due to filters
;; Skipped "_SC_MEMORY_PROTECTION" due to filters
;; Skipped "_POSIX_CLOCKRES_MIN" due to filters
;; Skipped "SEM_VALUE_MAX" due to filters
;; Skipped "_SC_SIGNALS" due to filters
;; Skipped "_SC_MEMLOCK_RANGE" due to filters
;; Skipped "_POSIX_TZNAME_MAX" due to filters
;; Skipped "LOGIN_NAME_MAX" due to filters
;; Skipped "_SC_MEMLOCK" due to filters
;; Skipped "_POSIX_TTY_NAME_MAX" due to filters
;; Skipped "_SC_SPAWN" due to filters
;; Skipped "_SC_AIO_MAX" due to filters
;; Skipped "TTY_NAME_MAX" due to filters
;; Skipped "_SC_SINGLE_PROCESS" due to filters
;; Skipped "_POSIX_TIMER_MAX" due to filters
;; Skipped "RE_DUP_MAX" due to filters
;; Skipped "_SC_AIO_LISTIO_MAX" due to filters
;; Skipped "_SC_NETWORKING" due to filters
;; Skipped "_POSIX_SYMLOOP_MAX" due to filters
;; Skipped "DELAYTIMER_MAX" due to filters
;; Skipped "_SC_SHARED_MEMORY_OBJECTS" due to filters
;; Skipped "_SC_READER_WRITER_LOCKS" due to filters
;; Skipped "_POSIX_SYMLINK_MAX" due to filters
;; Skipped "_SC_SEMAPHORES" due to filters
;; Skipped "_SC_REGEXP" due to filters
;; Skipped "_POSIX_STREAM_MAX" due to filters
;; Skipped "_SC_SPIN_LOCKS" due to filters
;; Skipped "MQ_PRIO_MAX" due to filters
;; Skipped "MAX_CANON" due to filters
;; Skipped "_SC_MQ_PRIO_MAX" due to filters
;; Skipped "_SC_TIMEOUTS" due to filters
;; Skipped "NGROUPS_MAX" due to filters
;; Skipped "_SC_MQ_OPEN_MAX" due to filters
;; Skipped "_SC_TYPED_MEMORY_OBJECTS" due to filters
;; Skipped "_POSIX2_EXPR_NEST_MAX" due to filters
;; Skipped "_LINUX_LIMITS_H" due to filters
;; Skipped "_SC_DELAYTIMER_MAX" due to filters
;; Skipped "_SC_USER_GROUPS" due to filters
;; Skipped "_POSIX2_COLL_WEIGHTS_MAX" due to filters
;; Skipped "_SC_AIO_PRIO_DELTA_MAX" due to filters
;; Skipped "_SC_USER_GROUPS_R" due to filters
;; Skipped "_SC_SEM_NSEMS_MAX" due to filters
;; Skipped "__have_pthread_attr_t" due to filters
;; Skipped "_SC_SPORADIC_SERVER" due to filters
;; Skipped "_SC_RTSIG_MAX" due to filters
;; Skipped "_SC_THREAD_SPORADIC_SERVER" due to filters
;; Skipped "_POSIX2_BC_SCALE_MAX" due to filters
;; Skipped "_SC_PAGE_SIZE" due to filters
;; Skipped "_POSIX2_BC_DIM_MAX" due to filters
;; Skipped "_SC_SYSTEM_DATABASE" due to filters
;; Skipped "_SC_PAGESIZE" due to filters
;; Skipped "HOST_NAME_MAX" due to filters
;; Skipped "_SC_SYSTEM_DATABASE_R" due to filters
;; Skipped "_SC_VERSION" due to filters
;; Skipped "_BITS_POSIX2_LIM_H" due to filters
;; Skipped "_SC_SYMLOOP_MAX" due to filters
;; Skipped "_POSIX2_BC_BASE_MAX" due to filters

;; "/usr/include/zlib.h:189:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_DEFAULT_COMPRESSION -1)

;; Skipped "_SC_STREAMS" due to filters
;; Skipped "_SC_2_PBS_TRACK" due to filters
;; Skipped "__u_char_defined" due to filters
;; Skipped "PTHREAD_STACK_MIN" due to filters
;; Skipped "__PTHREAD_MUTEX_HAVE_ELISION" due to filters
;; Skipped "CHARCLASS_NAME_MAX" due to filters
;; Skipped "_VA_LIST" due to filters
;; Skipped "_SC_V6_ILP32_OFF32" due to filters
;; Skipped "__STDARG_H" due to filters

;; "/usr/include/zlib.h:176:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_ERRNO -1)


;; "/usr/include/zlib.h:173:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_OK 0)

;; Skipped "_SC_2_PBS_CHECKPOINT" due to filters
;; Skipped "_POSIX2_LINE_MAX" due to filters
;; Skipped "_SC_2_PBS_ACCOUNTING" due to filters

;; "/usr/include/zlib.h:192:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_FILTERED 1)

;; Skipped "_POSIX2_BC_STRING_MAX" due to filters
;; Skipped "__PTHREAD_MUTEX_HAVE_PREV" due to filters
;; Skipped "_SC_2_PBS" due to filters

;; "/usr/include/zlib.h:175:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_NEED_DICT 2)


;; "/usr/include/zlib.h:169:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_BLOCK 5)

;; Skipped "_SC_2_PBS_MESSAGE" due to filters

;; "/usr/include/zlib.h:179:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_MEM_ERROR -4)


;; "/usr/include/zlib.h:194:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_RLE 3)


;; "/usr/include/zlib.h:195:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_FIXED 4)

;; Skipped "_SC_2_PBS_LOCATE" due to filters

;; "/usr/include/zlib.h:178:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_DATA_ERROR -3)


;; "/usr/include/zlib.h:202:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_UNKNOWN 2)


;; "/usr/include/zlib.h:170:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_TREES 6)

;; Skipped "__PTHREAD_RWLOCK_INT_FLAGS_SHARED" due to filters

;; "/usr/include/zlib.h:168:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_FINISH 4)

;; Skipped "UINT_MAX" due to filters
;; Skipped "LONG_MIN" due to filters

;; "/usr/include/zlib.h:200:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_TEXT 1)


;; "/usr/include/zlib.h:174:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_STREAM_END 1)


;; "/usr/include/zlib.h:210:9"

;; "/usr/include/zlib.h:187:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_BEST_SPEED 1)


;; "/usr/include/zlib.h:196:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_DEFAULT_STRATEGY 0)


;; "/usr/include/zlib.h:201:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_ASCII 1)


;; "/usr/include/zlib.h:193:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_HUFFMAN_ONLY 2)


;; "/usr/include/zlib.h:186:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_NO_COMPRESSION 0)

;; Skipped "_PC_MAX_CANON" due to filters
;; Skipped "_SC_V6_LP64_OFF64" due to filters

;; "/usr/include/zlib.h:199:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_BINARY 0)

;; Skipped "_SC_V6_ILP32_OFFBIG" due to filters
;; Skipped "_PC_MAX_INPUT" due to filters

;; "/usr/include/zlib.h:208:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_NULL 0)


;; "/usr/include/zlib.h:205:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_DEFLATED 8)

;; Skipped "_PC_LINK_MAX" due to filters
;; Skipped "Z_LFS64" due to filters
;; Skipped "LLONG_MIN" due to filters
;; Skipped "_PC_PIPE_BUF" due to filters
;; Skipped "z_off_t" due to filters
;; Skipped "ULLONG_MAX" due to filters
;; Skipped "LLONG_MAX" due to filters
;; Skipped "_PC_CHOWN_RESTRICTED" due to filters
;; Skipped "_PC_NAME_MAX" due to filters

;; "/usr/include/zlib.h:180:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_BUF_ERROR -5)

;; Skipped "CHAR_MAX" due to filters
;; Skipped "_PC_PATH_MAX" due to filters
;; Skipped "CHAR_BIT" due to filters
;; Skipped "_PC_ASYNC_IO" due to filters

;; "/usr/include/zlib.h:166:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_SYNC_FLUSH 2)


;; "/usr/include/zlib.h:177:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_STREAM_ERROR -2)

;; Skipped "_PC_PRIO_IO" due to filters
;; Skipped "CHAR_MIN" due to filters

;; "/usr/include/zlib.h:167:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_FULL_FLUSH 3)

;; Skipped "LONG_MAX" due to filters
;; Skipped "_PC_NO_TRUNC" due to filters
;; Skipped "ULONG_MAX" due to filters
;; Skipped "_PC_SYNC_IO" due to filters
;; Skipped "_PC_VDISABLE" due to filters

;; "/usr/include/zlib.h:164:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_NO_FLUSH 0)

;; Skipped "_PC_REC_INCR_XFER_SIZE" due to filters
;; Skipped "_POSIX_HOST_NAME_MAX" due to filters

;; "/usr/include/zlib.h:165:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT Z_PARTIAL_FLUSH 1)

;; Skipped "_PC_REC_MAX_XFER_SIZE" due to filters
;; Skipped "_POSIX_LINK_MAX" due to filters
;; Skipped "_PC_SOCK_MAXBUF" due to filters
;; Skipped "_POSIX_CHILD_MAX" due to filters
;; Skipped "_PC_FILESIZEBITS" due to filters
;; Skipped "_POSIX_DELAYTIMER_MAX" due to filters
;; Skipped "_POSIX_AIO_MAX" due to filters
;; Skipped "_PC_ALLOC_SIZE_MIN" due to filters
;; Skipped "__GNUC_VA_LIST" due to filters
;; Skipped "_POSIX_ARG_MAX" due to filters
;; Skipped "_PC_SYMLINK_MAX" due to filters
;; Skipped "_BITS_POSIX1_LIM_H" due to filters
;; Skipped "_PC_REC_MIN_XFER_SIZE" due to filters
;; Skipped "_POSIX_AIO_LISTIO_MAX" due to filters
;; Skipped "_PC_REC_XFER_ALIGN" due to filters

;; "/usr/include/zlib.h:41:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VERNUM 4736)


;; "/usr/include/zlib.h:40:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VERSION "1.2.8" :TEST 'COMMON-LISP:EQUAL)


;; "/usr/include/zlib.h:43:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VER_MINOR 2)


;; "/usr/include/zlib.h:42:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VER_MAJOR 1)


;; "/usr/include/zlib.h:45:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VER_SUBREVISION 0)


;; "/usr/include/zlib.h:44:9"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT ZLIB_VER_REVISION 8)

;; Skipped "z_off64_t" due to filters
;; Skipped "__SIZEOF_PTHREAD_RWLOCKATTR_T" due to filters
;; Skipped "__SIZEOF_PTHREAD_RWLOCK_T" due to filters
;; Skipped "__SIZEOF_PTHREAD_BARRIERATTR_T" due to filters
;; Skipped "__SIZEOF_PTHREAD_BARRIER_T" due to filters
;; Skipped "_LIBC_LIMITS_H_" due to filters
;; Skipped "_GCC_LIMITS_H_" due to filters
;; Skipped "MB_LEN_MAX" due to filters
;; Skipped "Z_U4" due to filters
;; Skipped "SCHAR_MIN" due to filters
;; Skipped "SCHAR_MAX" due to filters
;; Skipped "__CLANG_LIMITS_H" due to filters
;; Skipped "SHRT_MAX" due to filters
;; Skipped "INT_MIN" due to filters
;; Skipped "USHRT_MAX" due to filters
;; Skipped "UCHAR_MAX" due to filters
;; Skipped "SHRT_MIN" due to filters
;; Skipped "INT_MAX" due to filters
;; Skipped "ZEXTERN" due to filters
;; Skipped "Z_HAVE_STDARG_H" due to filters
;; Skipped "ZEXPORT" due to filters
;; Skipped "ZEXPORTVA" due to filters
;; Skipped "FAR" due to filters
;; Skipped "_SC_NZERO" due to filters
;; Skipped "_SC_SSIZE_MAX" due to filters
;; Skipped "_SC_WORD_BIT" due to filters
;; Skipped "_SC_LONG_BIT" due to filters
;; Skipped "_SC_MB_LEN_MAX" due to filters
;; Skipped "_SC_INT_MAX" due to filters
;; Skipped "_SC_INT_MIN" due to filters
;; Skipped "_SC_CHAR_MAX" due to filters
;; Skipped "_SC_CHAR_MIN" due to filters
;; Skipped "_SC_SCHAR_MAX" due to filters
;; Skipped "_SC_XOPEN_UNIX" due to filters
;; Skipped "_SC_XOPEN_CRYPT" due to filters
;; Skipped "_SC_XOPEN_VERSION" due to filters
;; Skipped "_SC_XOPEN_XCU_VERSION" due to filters
;; Skipped "_SC_AVPHYS_PAGES" due to filters
;; Skipped "_SC_ATEXIT_MAX" due to filters
;; Skipped "_SC_PASS_MAX" due to filters
;; Skipped "_SC_NPROCESSORS_ONLN" due to filters
;; Skipped "_SC_PHYS_PAGES" due to filters
;; Skipped "_SC_XOPEN_XPG4" due to filters
;; Skipped "_SC_CHAR_BIT" due to filters
;; Skipped "_SC_2_UPE" due to filters
;; Skipped "_SC_XOPEN_XPG2" due to filters
;; Skipped "_SC_XOPEN_XPG3" due to filters
;; Skipped "_SC_2_CHAR_TERM" due to filters
;; Skipped "_SC_2_C_VERSION" due to filters
;; Skipped "_SC_XOPEN_ENH_I18N" due to filters
;; Skipped "_SC_THREAD_KEYS_MAX" due to filters
;; Skipped "_SC_XOPEN_SHM" due to filters
;; Skipped "__sigset_t_defined" due to filters
;; Skipped "_SC_THREAD_DESTRUCTOR_ITERATIONS" due to filters
;; Skipped "_SC_THREAD_THREADS_MAX" due to filters
;; Skipped "_SC_THREAD_STACK_MIN" due to filters
;; Skipped "_SC_GETPW_R_SIZE_MAX" due to filters
;; Skipped "_SIGSET_NWORDS" due to filters
;; Skipped "_SC_GETGR_R_SIZE_MAX" due to filters
;; Skipped "_SIGSET_H_types" due to filters
;; Skipped "_SC_TTY_NAME_MAX" due to filters
;; Skipped "_SC_LOGIN_NAME_MAX" due to filters
;; Skipped "_SC_THREAD_PRIO_PROTECT" due to filters
;; Skipped "_SC_THREAD_PRIO_INHERIT" due to filters
;; Skipped "_SC_NPROCESSORS_CONF" due to filters
;; Skipped "_SC_THREAD_PROCESS_SHARED" due to filters
;; Skipped "_SC_THREAD_ATTR_STACKADDR" due to filters
;; Skipped "_SC_THREAD_PRIORITY_SCHEDULING" due to filters
;; Skipped "_SC_THREAD_ATTR_STACKSIZE" due to filters
;; Skipped "_SC_POLL" due to filters
;; Skipped "_POSIX_TRACE_EVENT_FILTER" due to filters
;; Skipped "_POSIX_TRACE" due to filters
;; Skipped "_SC_PII_OSI" due to filters
;; Skipped "_POSIX_THREAD_SPORADIC_SERVER" due to filters
;; Skipped "_SC_IOV_MAX" due to filters
;; Skipped "_SC_SELECT" due to filters
;; Skipped "_SC_UIO_MAXIOV" due to filters
;; Skipped "NFDBITS" due to filters
;; Skipped "_SC_PII_XTI" due to filters
;; Skipped "_SC_PII" due to filters
;; Skipped "FD_SETSIZE" due to filters
;; Skipped "_SC_PII_INTERNET" due to filters
;; Skipped "_SC_PII_SOCKET" due to filters
;; Skipped "__NFDBITS" due to filters
;; Skipped "_POSIX_V6_LP64_OFF64" due to filters
;; Skipped "_SC_T_IOV_MAX" due to filters
;; Skipped "_POSIX_V7_LP64_OFF64" due to filters
;; Skipped "__suseconds_t_defined" due to filters
;; Skipped "_SC_PII_OSI_M" due to filters
;; Skipped "_XBS5_LPBIG_OFFBIG" due to filters
;; Skipped "_SC_THREAD_SAFE_FUNCTIONS" due to filters
;; Skipped "_POSIX_V6_LPBIG_OFFBIG" due to filters
;; Skipped "_SC_THREADS" due to filters
;; Skipped "_STRUCT_TIMEVAL" due to filters
;; Skipped "_POSIX_V7_LPBIG_OFFBIG" due to filters
;; Skipped "_SC_PII_INTERNET_DGRAM" due to filters
;; Skipped "_POSIX_TYPED_MEMORY_OBJECTS" due to filters
;; Skipped "_SC_PII_INTERNET_STREAM" due to filters
;; Skipped "_POSIX_TRACE_LOG" due to filters
;; Skipped "_SC_PII_OSI_CLTS" due to filters
;; Skipped "_POSIX_TRACE_INHERIT" due to filters
;; Skipped "_SC_PII_OSI_COTS" due to filters
;; Skipped "_SC_BC_DIM_MAX" due to filters
;; Skipped "_SC_BC_SCALE_MAX" due to filters
;; Skipped "_SC_BC_STRING_MAX" due to filters
;; Skipped "_SC_COLL_WEIGHTS_MAX" due to filters
;; Skipped "_SC_SEM_VALUE_MAX" due to filters
;; Skipped "STDC" due to filters
;; Skipped "STDC99" due to filters
;; Skipped "_SC_SIGQUEUE_MAX" due to filters
;; Skipped "_SC_TIMER_MAX" due to filters
;; Skipped "_SC_BC_BASE_MAX" due to filters
;; Skipped "_SC_2_C_DEV" due to filters
;; Skipped "_SC_SCHAR_MIN" due to filters
;; Skipped "z_const" due to filters
;; Skipped "_SC_2_FORT_DEV" due to filters
;; Skipped "_SC_2_FORT_RUN" due to filters
;; Skipped "_SC_2_LOCALEDEF" due to filters
;; Skipped "_SC_2_SW_DEV" due to filters
;; Skipped "_SC_RE_DUP_MAX" due to filters
;; Skipped "_SC_ULONG_MAX" due to filters
;; Skipped "_SC_EQUIV_CLASS_MAX" due to filters
;; Skipped "_SC_CHARCLASS_NAME_MAX" due to filters
;; Skipped "_SC_UCHAR_MAX" due to filters
;; Skipped "_SC_EXPR_NEST_MAX" due to filters
;; Skipped "_SC_LINE_MAX" due to filters
;; Skipped "_SC_2_VERSION" due to filters
;; Skipped "_SC_SHRT_MIN" due to filters
;; Skipped "_SC_SHRT_MAX" due to filters
;; Skipped "_SC_2_C_BIND" due to filters
;; Skipped "_SC_UINT_MAX" due to filters
;; Skipped "_SC_NL_MSGMAX" due to filters
;; Skipped "_SC_NL_LANGMAX" due to filters
;; Skipped "_SC_NL_ARGMAX" due to filters
;; Skipped "F_ULOCK" due to filters
;; Skipped "F_TLOCK" due to filters
;; Skipped "_SC_USHRT_MAX" due to filters

;; "/usr/include/x86_64-linux-gnu/zconf.h:247:11"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT MAX_WBITS 15)

;; Skipped "F_LOCK" due to filters
;; Skipped "_SC_XBS5_ILP32_OFF32" due to filters

;; "/usr/include/x86_64-linux-gnu/zconf.h:237:13"
(ALEXANDRIA.0.DEV:DEFINE-CONSTANT MAX_MEM_LEVEL 9)

;; Skipped "_SC_NL_TEXTMAX" due to filters
;; Skipped "F_TEST" due to filters
;; Skipped "_SC_NL_SETMAX" due to filters
;; Skipped "_SC_NL_NMAX" due to filters
;; Skipped "ZCONF_H" due to filters
;; Skipped "_SC_XOPEN_LEGACY" due to filters
;; Skipped "_SC_XBS5_LPBIG_OFFBIG" due to filters

;; "/usr/include/zlib.h:32:9"
;; Skipped "_SC_XBS5_LP64_OFF64" due to filters
;; Skipped "_SC_BASE" due to filters
;; Skipped "_SC_XBS5_ILP32_OFFBIG" due to filters
;; Skipped "_SC_BARRIERS" due to filters
;; Skipped "_SC_ADVISORY_INFO" due to filters
;; Skipped "_SC_XOPEN_REALTIME_THREADS" due to filters
;; Skipped "_SC_XOPEN_REALTIME" due to filters
(COMMON-LISP:EXPORT 'COMMON-LISP:NIL '#:HU.DWIM.ZLIB.FFI)

(COMMON-LISP:DEFPARAMETER +FUNCTION-NAMES+
  '(("deflateResetKeep" . |deflateResetKeep|) ("inflateResetKeep" . |inflateResetKeep|) ("inflateUndermine" . |inflateUndermine|)
    ("get_crc_table" . |get_crc_table|) ("inflateSyncPoint" . |inflateSyncPoint|) ("zError" . |zError|) ("gzoffset" . |gzoffset|) ("gztell" . |gztell|)
    ("gzopen" . |gzopen|) ("gzgetc_" . |gzgetc_|) ("inflateBackInit_" . |inflateBackInit_|) ("inflateInit2_" . |inflateInit2_|)
    ("deflateInit2_" . |deflateInit2_|) ("inflateInit_" . |inflateInit_|) ("deflateInit_" . |deflateInit_|) ("crc32" . |crc32|) ("adler32" . |adler32|)
    ("gzclearerr" . |gzclearerr|) ("gzerror" . |gzerror|) ("gzclose_w" . |gzclose_w|) ("gzclose_r" . |gzclose_r|) ("gzclose" . |gzclose|)
    ("gzdirect" . |gzdirect|) ("gzeof" . |gzeof|) ("gzrewind" . |gzrewind|) ("gzflush" . |gzflush|) ("gzungetc" . |gzungetc|) ("gzgetc" . |gzgetc|)
    ("gzputc" . |gzputc|) ("gzgets" . |gzgets|) ("gzputs" . |gzputs|) ("gzprintf" . |gzprintf|) ("gzread" . |gzread|) ("gzsetparams" . |gzsetparams|)
    ("gzbuffer" . |gzbuffer|) ("gzdopen" . |gzdopen|) ("uncompress" . |uncompress|) ("compressBound" . |compressBound|) ("compress2" . |compress2|)
    ("compress" . |compress|) ("zlibCompileFlags" . |zlibCompileFlags|) ("inflateBackEnd" . |inflateBackEnd|) ("inflateBack" . |inflateBack|)
    ("inflateGetHeader" . |inflateGetHeader|) ("inflateMark" . |inflateMark|) ("inflatePrime" . |inflatePrime|) ("inflateReset2" . |inflateReset2|)
    ("inflateReset" . |inflateReset|) ("inflateCopy" . |inflateCopy|) ("inflateSync" . |inflateSync|) ("inflateGetDictionary" . |inflateGetDictionary|)
    ("inflateSetDictionary" . |inflateSetDictionary|) ("deflateSetHeader" . |deflateSetHeader|) ("deflatePrime" . |deflatePrime|)
    ("deflatePending" . |deflatePending|) ("deflateBound" . |deflateBound|) ("deflateTune" . |deflateTune|) ("deflateParams" . |deflateParams|)
    ("deflateReset" . |deflateReset|) ("deflateCopy" . |deflateCopy|) ("deflateSetDictionary" . |deflateSetDictionary|) ("inflateEnd" . |inflateEnd|)
    ("inflate" . |inflate|) ("deflateEnd" . |deflateEnd|) ("deflate" . |deflate|) ("zlibVersion" . |zlibVersion|)))

(COMMON-LISP:DEFPARAMETER +STRUCT-NAMES+
  '(("gzFile_s" . |gzFile_s|) ("gz_header_s" . |gz_header_s|) ("z_stream_s" . |z_stream_s|) ("internal_state" . |internal_state|)))

(COMMON-LISP:DEFPARAMETER +UNION-NAMES+ 'COMMON-LISP:NIL)

(COMMON-LISP:DEFPARAMETER +VARIABLE-NAMES+ 'COMMON-LISP:NIL)

(COMMON-LISP:DEFPARAMETER +TYPE-NAMES+
  '(("va_list" . |va_list|) ("z_crc_t" . |z_crc_t|) ("off_t" . |off_t|) ("voidpc" . |voidpc|) ("gzFile" . |gzFile|) ("out_func" . |out_func|)
    ("in_func" . |in_func|) ("gz_headerp" . |gz_headerp|) ("gz_header" . |gz_header|) ("z_streamp" . |z_streamp|) ("z_stream" . |z_stream|) ("Bytef" . |Bytef|)
    ("free_func" . |free_func|) ("alloc_func" . |alloc_func|) ("voidp" . |voidp|) ("voidpf" . |voidpf|) ("uLongf" . |uLongf|) ("uIntf" . |uIntf|)
    ("uLong" . |uLong|) ("uInt" . |uInt|)))

(COMMON-LISP:DEFPARAMETER +CONSTANT-NAMES+
  '(("MAX_MEM_LEVEL" . MAX_MEM_LEVEL) ("MAX_WBITS" . MAX_WBITS) ("ZLIB_VER_REVISION" . ZLIB_VER_REVISION) ("ZLIB_VER_SUBREVISION" . ZLIB_VER_SUBREVISION)
    ("ZLIB_VER_MAJOR" . ZLIB_VER_MAJOR) ("ZLIB_VER_MINOR" . ZLIB_VER_MINOR) ("ZLIB_VERSION" . ZLIB_VERSION) ("ZLIB_VERNUM" . ZLIB_VERNUM)
    ("Z_PARTIAL_FLUSH" . Z_PARTIAL_FLUSH) ("Z_NO_FLUSH" . Z_NO_FLUSH) ("Z_FULL_FLUSH" . Z_FULL_FLUSH) ("Z_STREAM_ERROR" . Z_STREAM_ERROR)
    ("Z_SYNC_FLUSH" . Z_SYNC_FLUSH) ("Z_BUF_ERROR" . Z_BUF_ERROR) ("Z_DEFLATED" . Z_DEFLATED) ("Z_NULL" . Z_NULL) ("Z_BINARY" . Z_BINARY)
    ("Z_NO_COMPRESSION" . Z_NO_COMPRESSION) ("Z_HUFFMAN_ONLY" . Z_HUFFMAN_ONLY) ("Z_ASCII" . Z_ASCII) ("Z_DEFAULT_STRATEGY" . Z_DEFAULT_STRATEGY)
    ("Z_BEST_SPEED" . Z_BEST_SPEED) ("Z_STREAM_END" . Z_STREAM_END) ("Z_TEXT" . Z_TEXT) ("Z_FINISH" . Z_FINISH) ("Z_TREES" . Z_TREES) ("Z_UNKNOWN" . Z_UNKNOWN)
    ("Z_DATA_ERROR" . Z_DATA_ERROR) ("Z_FIXED" . Z_FIXED) ("Z_RLE" . Z_RLE) ("Z_MEM_ERROR" . Z_MEM_ERROR) ("Z_BLOCK" . Z_BLOCK) ("Z_NEED_DICT" . Z_NEED_DICT)
    ("Z_FILTERED" . Z_FILTERED) ("Z_OK" . Z_OK) ("Z_ERRNO" . Z_ERRNO) ("Z_DEFAULT_COMPRESSION" . Z_DEFAULT_COMPRESSION)
    ("Z_BEST_COMPRESSION" . Z_BEST_COMPRESSION) ("Z_VERSION_ERROR" . Z_VERSION_ERROR)))

(COMMON-LISP:DEFPARAMETER +ARGUMENT-NAMES+
  '(("window" . |window|) ("memLevel" . |memLevel|) ("method" . |method|) ("stream_size" . |stream_size|) ("version" . |version|) ("crc" . |crc|)
    ("adler" . |adler|) ("errnum" . |errnum|) ("c" . |c|) ("s" . |s|) ("format" . |format|) ("len" . |len|) ("buf" . |buf|) ("size" . |size|) ("file" . |file|)
    ("mode" . |mode|) ("fd" . |fd|) ("destLen" . |destLen|) ("out_desc" . |out_desc|) ("out" . |out|) ("in_desc" . |in_desc|) ("in" . |in|)
    ("windowBits" . |windowBits|) ("head" . |head|) ("value" . |value|) ("bits" . |bits|) ("pending" . |pending|) ("sourceLen" . |sourceLen|)
    ("max_chain" . |max_chain|) ("nice_length" . |nice_length|) ("max_lazy" . |max_lazy|) ("good_length" . |good_length|) ("strategy" . |strategy|)
    ("level" . |level|) ("source" . |source|) ("dest" . |dest|) ("dictLength" . |dictLength|) ("dictionary" . |dictionary|) ("flush" . |flush|)
    ("strm" . |strm|)))

(COMMON-LISP:DEFPARAMETER +FIELD-NAMES+
  '(("dummy" . |dummy|) ("next" . |next|) ("have" . |have|) ("done" . |done|) ("hcrc" . |hcrc|) ("comm_max" . |comm_max|) ("comment" . |comment|)
    ("name_max" . |name_max|) ("name" . |name|) ("extra_max" . |extra_max|) ("extra_len" . |extra_len|) ("extra" . |extra|) ("os" . |os|) ("xflags" . |xflags|)
    ("time" . |time|) ("text" . |text|) ("reserved" . |reserved|) ("adler" . |adler|) ("data_type" . |data_type|) ("opaque" . |opaque|) ("zfree" . |zfree|)
    ("zalloc" . |zalloc|) ("state" . |state|) ("msg" . |msg|) ("total_out" . |total_out|) ("avail_out" . |avail_out|) ("next_out" . |next_out|)
    ("total_in" . |total_in|) ("avail_in" . |avail_in|) ("next_in" . |next_in|)))

